---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pfdecomp

UNDER CONSTRUCTION - come back later...

<!-- badges: start -->
<!-- badges: end -->

The goal of pfdecomp is to decompose production functions into contributions to growth from each of the factors...

## Installation

You can install the development version of pfdecomp from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("xprimexinverse/pfdecomp")
```

## Example

This is a basic example which shows you how to perform growth accounting for Ireland using data from AMECO:

```{r example}
library(pfdecomp)
library(ecmacro)

OVGD <- get_series(AMECO_spring_2024, "IRL.1.1.0.0.OVGD")
OKND <- get_series(AMECO_spring_2024, "IRL.1.0.0.0.OKND")
NLHT <- get_series(AMECO_spring_2024, "IRL.1.0.0.0.NLHT")

cd07 <- cobb_douglas(y = window(OVGD, start = 1970), k = window(OKND, start = 1970), l = window(NLHT, start = 1970), beta = 0.7, figure = FALSE)

cd07@contribs

cd07@avg_gr

```

